### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by TolisChal** [TolisChal/volume_approximation#4]
- [x]  Create organization and three repositories to organize the code in more efficient way
- [x] Create tests in R
- [x] Add algorithms from socg 18 paper
- [x] Improve R documentation (table of contents, package description)
- [x] Use .hpp file in test to avoid repeating the same part of code.
- [x] Change typedefs before includes in volume.h.
- [x] Add generator function for Birkhoff polytopes.

**Comment by vissarion** [comment]
- [ ] Re-factoring current code (e.g. remove `var` struct for passing parameters)
- [ ] Linear extensions functionality
